<?php

namespace Rii\ReportBundle\Repository;

use Rii\PropertyBundle\Repository\EntityRepository;

/**
 * ContableAsientoAdminMovRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContableAsientoAdminMovRepository extends EntityRepository
{
    function __construct($app) {
        parent::__construct($app);
        $this->tableName = "contable_administrativas_mov";
        $this->tableId = "movimiento";
    }

	public function getAllWithDebeHaberOriginal($fromDate, $toDate, $inmobiliaria, $sucursal) {
        $queryStr = "SELECT  cue.*,  sum(mov.debe_original)+0 as debe, sum(mov.haber_original)+0 as haber, mov.moneda_original
             FROM contable_administrativas_mov mov
             INNER JOIN contable_cuentas_administrativas cue
             ON mov.cuenta = cue.cuenta
             WHERE mov.borrado = 'N'  AND cue.borrado = 'N'
             AND mov.inmobiliaria = :inmobiliaria AND mov.sucursal = :sucursal
             AND mov.fecha_hora >= :date_from AND mov.fecha_hora < :date_to
             GROUP BY cue.nro_cuenta
             ORDER BY cue.nro_cuenta ASC";
        $stmt = $this->app['db']->prepare($queryStr);
        $stmt->bindValue("date_from", $fromDate->format('Y-m-d H:i:s'));
        $stmt->bindValue("date_to", $toDate->format('Y-m-d H:i:s'));
        $stmt->bindValue("inmobiliaria", $inmobiliaria);
        $stmt->bindValue("sucursal", $sucursal);
        $stmt->execute();
        $var = $stmt->fetchAll();
        return $var;
    }

}
