<?php

namespace Rii\ReportBundle\Repository;

use Rii\PropertyBundle\Repository\EntityRepository;
/**
 * ContableConfiguracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContableConfiguracionRepository extends EntityRepository
{

    function __construct($app) {
        parent::__construct($app);
        $this->tableName = "contable_configuracion";
        $this->tableId = "config";
    }

    function getMyConfig(){
        $query = "SELECT * FROM ".$this->tableName." ORDER BY ".$this->tableId." DESC LIMIT 1;";
        $stmt = $this->app['db'];
        return $stmt->fetchAssoc($query);
    }

}
