# app
app:
    mode: dev

# db
database:
    driver: pdo_mysql
    host: localhost
    dbname: amulen_light_dev
    user: root
    password: root
    
# security
security:
    enabled: false
    login_path: /login
    
properties:
    sitename: Amulen light
    example_prop: "example"