<?php

namespace Rii\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContableConfiguracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContableConfiguracionRepository extends EntityRepository
{
	    function getMyConfig(){
	        $em = $this->getEntityManager();
	        $qb = $em->createQueryBuilder();
	        $query = $qb->select(array('config'))
	            ->from('RiiReportBundle:ContableConfiguracion','config')
	            ->setMaxResults(1)
	            ->orderBy("config.id", "desc")
	            ->getQuery();
	        return $query->getOneOrNullResult();
	    }
}
